### ISSUE TITLE
Please rebase to linux/master or wireless-drivers-next/master

### ISSUE THREAD

**Issue by khfeng** [rtlwifi-linux/rtw88_8723de#1]
I'd like to backport 8723de support to Ubuntu's unstable kernel branch [1].
So please rebase this repo on top of mainline or wireless-drivers-next.

[1] https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/unstable/

**Comment by pkshih** [comment]
Which kernel version do you want to apply?

This repo is based on kernel 5.2+, and verified by our QC.
If I do rebase, it's hard to guarantee the quality.
My opinion is to apply this driver directly (don't rebase) if your kernel older than 5.2.

Or, please share your backport process. We can discuss how to meet your requirement.

**Comment by khfeng** [comment]
The plan is to have 8723de support in Ubuntu Focal (20.04) LTS, which uses Linux kernel v5.4.

We currently need to support two transient kernels, based on ~~v4.15~~ and v5.0. I can merge this repo cleanly to both of them, so this is not a problem.
 
As they are transient, both kernels will be replaced by the v5.4 based kernel once 20.04 LTS released.

So the easiest way (at least for me) is to have two branches, the current one as is, and another one based on v5.4.

**Comment by pkshih** [comment]
Linux v5.4 is still in RC stage, so we may need to wait for 3 or 4 weeks, right?

At that time, I'll add another branch like 'base-v5.4' and do rebase.
Does it make sense?

**Comment by khfeng** [comment]
> Linux v5.4 is still in RC stage, so we may need to wait for 3 or 4 weeks, right?

It's currently -rc4 so internal API should be stable enough.

> At that time, I'll add another branch like 'base-v5.4' and do rebase.
> Does it make sense?

Yes, that will be really helpful.

**Comment by anthonywong** [comment]
Hi pkshih,

> Or, please share your backport process. We can discuss how to meet your requirement.

Our backport process requires the driver to be accepted by upstream and landed there, then we can backport it from upstream's mainline/stable back to our 5.4 kernel.

README.md of this project says "this repository are going to submit to upstream soon", do you have a time frame for that? You will need to rebase to mainline or wireless-drivers-next eventually before you submit to upstream.

**Comment by pkshih** [comment]
Since kernel 5.4 is -rc8 now, it's impossible to be merged, the alternative way is to do rebase this repository to 5.4 as mentioned before. Currently, I had done rebase to 5.4-rc7 early, and will do rebase again when 5.4 is released.

8723DE is under review internally. It may be partial upstream in kernel 5.6.

**Comment by pkshih** [comment]
I create a new branch 'base-v5.4' for your request.

We run 8822BE/8822CE/8723DE on this branch, and they work well.

**Comment by khfeng** [comment]
I tried to cherry-pick these patches to Linux v5.4, but there are just way too many conflicts.

Can you please share the sha1sum of the base?
Or is it possible to rebase on mainline v5.4?

**Comment by pkshih** [comment]
The base is 524d4e683a1e26 ("rtw88: configure firmware after HCI started") in 'base-v5.4' branch.

**Comment by khfeng** [comment]
Oops, I forgot to switch to branch base-v5.4 :(
Everything's good now. Sorry about that.
