### ISSUE TITLE
Please rebase v5.4-base on top of upstream stable v5.4 branch.

### ISSUE THREAD

**Issue by khfeng** [rtlwifi-linux/rtw88_8723de#4]
There are many commits in v5.4-base are merged into upstream v5.4, however some of them are different, some even cause conflicts.

So let's rebase the v5.4-base on top of v5.4.y stable branch [1].

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-5.4.y

**Comment by pkshih** [comment]
It will be a force update to do rebase v5.4-base on top of v5.4.y.
How about do rebase v5.4.11 or something? Or you don't care force update?
What do you think?

**Comment by khfeng** [comment]
v5.4.11 should be sufficient.

**Comment by pkshih** [comment]
A new branch base-v5.4.11 is added.

**Comment by khfeng** [comment]
I have to apologize, I didn't think this through.

What I really want is to have it to rebase on mainline kernel.

Because many commits in this repo are already in Linus' tree, so we need to cherry-pick upstream commit in favor of out-of-tree commits.

So is it possible to rebase on top of mainline?

**Comment by pkshih** [comment]
I want to know the rule you do cherry-pick upstream commits. 
I think stable kernel will be better than mainline, right?
Or, you want to cherry-pick all commits merged in mainline? If so, your tree isn't *stable*, right?

**Comment by khfeng** [comment]
> I want to know the rule you do cherry-pick upstream commits.
> I think stable kernel will be better than mainline, right?

If a commit is in upstream then we should use it instead.
Say, [1] is in favor of [2], so `git cherry-pick` can log with correct sha1, i.e. "(cherry-picked from 3c519605850890160848a89690056afa204d0ef6)" line.

> Or, you want to cherry-pick all commits merged in mainline? If so, your tree isn't _stable_, right?
Yes, I want to cherry-pick all commits if it's already in mainline.
The source tree is mainline, the target tree is Ubuntu's 20.04 branch which is essentially stable tree v5.4.y.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3c519605850890160848a89690056afa204d0ef6
[2] https://github.com/rtlwifi-linux/rtw88_8723de/commit/7838b45264ea496d77210b2865b943fb724f4693

**Comment by pkshih** [comment]
Assume there are commit A-B-C-D in this repository, and A and C are merged into upstream called A' and C'.
Then, we do cherry-pick A' and C', the possible results may be 
1) A'-B-C'-D
2) A'-C'-B-D

I think you may choose 2), but I wonder if the sha1 is equal to the one in upstream.

**Comment by khfeng** [comment]
If both are the same functionality-wise, then 2) is preferred.

For sake of backporting, it'll be even better if it can be maintained like nouveau tree [1].

[1] https://github.com/skeggsb/linux/tree/linux-5.6

**Comment by pkshih** [comment]
> If both are the same functionality-wise, then 2) is preferred.

I'll spend some time to check which one is better.
If there's any update, I will let you know.

> For sake of backporting, it'll be even better if it can be maintained like nouveau tree [1].
> 
> [1] https://github.com/skeggsb/linux/tree/linux-5.6
> 

I think it isn't too hard to merge the code from this repository to kernel tree.
Since our resource is limited, we don't have plan to maintain 8723de within a kernel tree.

**Comment by pkshih** [comment]
I tried to do rebase to mainline, but the result isn't expected.

Assume: 
GitHub tree is X-A-B-D-E-F-G.
Mainline tree is X-C-D'  (D' is derived from D)
D' depends on C
F depends on D'

What's the expected result?
A possible result may be X-A-B-C-D'-E-F"-G, but the changes are quite big.

So, I think I can create another branch to hold my internal tree that has been done rebase mainline, if you want to have a tree based on mainline.

**Comment by khfeng** [comment]
> So, I think I can create another branch to hold my internal tree that has been done rebase mainline, if you want to have a tree based on mainline.

Yes, that'll be much nicer to work on.

**Comment by khfeng** [comment]
Any news on this?

**Comment by pkshih** [comment]
I think I can upload a new branch before next Monday.

**Comment by pkshih** [comment]
An new branch base-v5.6-rc1 is uploaded. 

Since the commit ("mac80211: simplify TX aggregation start") changes drivers and mac80211,
you need to merge it into mac80211 as well to make rtw88 works properly.

**Comment by khfeng** [comment]
It works great. Thanks.

Unrelated questions:
Will 8723DE support land at 5.7?
And which version is targeted for 8821CE support?

**Comment by pkshih** [comment]
> Will 8723DE support land at 5.7?

If you check commits of branch-v5.6-rc1, there are about ten commits prior to 8723DE.
And, current is -rc2, so it is possible to submit 8723DE before merge window. 
But, I can't expect how long reviewers can merge them.

> And` which version is targeted for 8821CE support?

We are doing rebase to the top of 8723DE, and going to review internally.
Then, it can be submitted just after 8723DE is merged.
